name: hpcl_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  progress_dialog: ^1.2.4
  cupertino_icons: ^1.0.5
  fluttertoast: ^8.2.2
  dio: ^5.2.1+1
  date_time_picker: ^2.1.0
  autocomplete_textfield: ^2.0.1
  dropdownfield: ^1.0.0
  package_info: ^2.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  image_picker: ^0.8.8
  sqflite: ^2.2.8+4
  http: ^0.13.6
  firebase_remote_config: ^4.2.2
  flutter_easyloading: ^3.0.5
  dotted_border: ^2.0.0+3
  collection: ^1.17.0
  get_storage: ^2.1.1
  device_info_plus: ^9.0.2
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.11
  intl: ^0.17.0
  connectivity_plus: ^4.0.1
  password_validated_field: ^0.0.3
  permission_handler: ^10.4.1
  flutter_image_compress: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator:
  retrofit_generator: any
  auto_route_generator: ^7.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/ic_launcher.png
    - assets/images/place_holder.png

