import '../../ExportFile/export_file.dart';

class AppStrings{

  static Position position =  position;
  static String locationLat ='Latitude';
  static String locationLong ='Longitude';
  static String star = "*";
  static String areaLabel = star + 'Select Area';
  static String docTypeLabel = 'Select Doc Type';
  static String chargeAreaLabel = star + 'Select Charge Area';
  static String getAllDistrictLabel = star + 'All District';
  static String mobileNoLabel = star + "Mobile No";
  static String firstNameLabel = star + 'First Name';
  static String middleNameLabel = 'Middle Name';
  static String lastNameLabel = star + 'Last Name';
  static String guardianTypeLabel = star + 'Select Guardian';
  static String guardianNameLabel = star + 'Guardian Name';
  static String emailAddressLabel = 'Email Address';
  static String houseNumberLabel = star + 'House Number';
  static String addressLabel = star + 'Locality/Sector';
  static String propertyCategoryLabel = 'Property Category';
  static String interestedLabel = 'Interested';
  static String reasonLabel = 'Reason';
  static String propertyClassLabel = 'Property Class';
  static String localityLabel = 'Locality';
  static String townLabel = 'Town';
  static String pinCodeLabel = star + 'Pin Code';
  static String districtLabel = star +'District';
  static String mdpeAllowLabel = star +'Society Allows MDPE';
  static String residentStatusLabel = 'Select Resident Status';
  static String noOfKitchenLabel = 'Number of Kitchen';
  static String noOfBathroomLabel = 'Number of Bathroom';
  static String existingCookingFuelLabel = 'Existing Cooking Fuel';
  static String noOfFamilyMembersLabel = 'Number of Family Members';
  static String locationCoordinatesLabel = 'Location coordinates';
  static String longitudeLabel = 'Longitude';
  static String latitudeLabel = 'Latitude';
  static String getLocationLabel = 'Location';
  static String landmarkLabel = 'Nearest Landmark';
  static String idProofHeading =  star +'Identification Proof';
  static String idProofNo = 'Id Proof No';
  static String idFrontImgSide = star + 'IdFrontImgSide';
  static String idBackImgSide =  star +'IdBackImgSide';
  static String ownershipProofHeading = 'Ownership Proof';
  static String ownershipProofNo = 'Ownership Proof No';
  static String electricBillFrontImg = 'Electric Bill Front Img';
  static String electricBillBackImgLabel = 'Electric Bill Back Img';
  static String customerBankNameLabel =  star +'Select Customer Bank Name';
  static String bankNameLabel =  'Select Bank Name';
  static String customerAccountNoLabel =  star +'Bank Account Number';
  static String mICRCodeLabel =  star +'MICR Code';
  static String customerIfscCodeLabel =  star +'Customer IFSC Code';
  static String  customerBankAddress = 'Customer Bank Address';
  static String  billingModeLabel =  star +'Prefered Billing Mode';
  static String conversionPolicyLabel = 'accept conversion Policy';
  static String fittingCostLabel = 'accept extra fitting cost';
  static String submit = 'Submit';
  static String nocLabel = 'NOC';
  static String nocProofNoLabel = 'NOC Proof No';
  static String doc3FrontImgSide = 'NOC Front Img';
  static String doc3BackImgSide = 'NOC Back Img';
  static String customerConsentLabel =  "Customer Consent";
  static String securityDepositLabel =  "Security Deposit";
  static String consentPhotoLabel =  star +'Consent Photo';
  static String chqCancelledPhotoLabel = 'Cancelled Cheque Photo';
  static String chqPhotoLabel =  star +'Cheque Photo';
  static String formStatusLabel = '';
  static String depositStatusLabel = 'Deposit Status';
  static String modeOfDepositLabel = 'Mode of Deposit';
  static String depositDateLabel =  star +'Cheque Date';
  static String depositTypeLabel =  star +'Deposit Type';
  static String depositAmountControllerLabel =  star +'Deposit Amount';
  static String chqNoLabel = 'Cheque No';
  static String chqBankLabel = '';
  static String accountNoLabel = 'Account No';
  static String btnLabel = '';
  static String feeChargeLabel = '';
  static String schemeType = '';
  static String schemeCode = '';
  static String depositName = 'Deposit Name';
  static String equipmentDepositAmount = 'Equipment Deposit Amount';
  static String interestAmount = '';
  static String registrationGST = '';
  static String totalAmount = '';
  static String nextCycleAmount = '';
  static String registrationTaxName = '';
  static String interestTaxAmt = '';
  static String regTax = '';
  static String msgSchemeDetail = 'Scheme Detail';
  static String depositAmountController = "Deposit Amount";
  static String depositAmount = "";
  static String noImage = 'No Image Found';
  static String formattedTime = '';
  static String formattedDate = '';
  static String dateAndTime = '';
  static  String bannerImagePath = '';
  static  String    frontImagePath = '';
  static  String   backImagePath = '';
  static  String    profileImagePath1 = '';
  static  String     profileImagePath3 = '';
  static  String    electricBillBackImgPath = '';
  static  String    profileImagePath5 = '';
  static  String   profileImagePath6 = '';
  static  String    profileImagePath7 = '';
  static  String   profileImagePath8 = '';
  static  String   profileImagePath9 = '';
  static  String    kycImagePath = '';
  static   File frontImage;
  static   File  backImage;
  static   File     profileImage3;
  static   File    electricBillBackImg;
  static   File   profileImage5;
  static   File     profileImage6;
  static   File   profileImage7;
  static   File   profileImage8;
  static   File   profileImage9;
}